### ISSUE TITLE
[Issue] crash without crash report apparently caused when you use HBM's Nuclear Tech Mod

### ISSUE THREAD

**Issue by gatoborrachon** [Kaydax/Ido#54] opened 2020-10-29 20:43 UTC
ISSUE: 
when you get in water the screen turn into the sky color (blue, strong blue, orange, etc) and minecraft simply stops working

i wanted to link a video but i cant record it, when the game crash there's no crash report, but i can provide you with the log:
(i think that the crash starts in the line 50 and its because of HBM's Nuclear Tech Mod (should i tell this to the dev of that mod?))
https://pastebin.com/9STkJeTJ

but if you want the complete log here is another link:
http://www.mediafire.com/file/wujvgvr31u4qgwn/latest.log/file

FORGE: 14.23.5.2854
IDO: 1.1.0
HBM: 1.3.7.1a
 
also, i can tell you that the mod BetterDiving add a similar mechanic of swiming, with that mod there's no issue so at least we know that is possible to fix this, maybe when you rewrite the mod with Obfuscated lib this issue will be solved

**Comment by Kaydax** [comment] 2020-10-29 21:26
This is caused by the way we used to handle animating the player while swimming and crawling. The HBM developer can choose to fix this issue for the current version of Ido, but I am currently working on fixing the many incompatibility's

**Comment by Kaydax** [comment] 2020-10-30 19:36
Crash seems to be fixed in the latest build

**Closed by Kaydax** 2020-10-30 19:36 UTC
Labels: incompatibility, known issue, multiplayer, singleplayer
